// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96VX1CNE8eoRciqZf64GjCXa7FIfsRc4',
    appId: '1:471763509371:web:dad781aeac54c4c34842de',
    messagingSenderId: '471763509371',
    projectId: 'backendcip-874bf',
    authDomain: 'backendcip-874bf.firebaseapp.com',
    storageBucket: 'backendcip-874bf.firebasestorage.app',
    measurementId: 'G-R56CBYPWRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnAaXiNAzpZoSPlE5SK51mbWQkJ3moqbk',
    appId: '1:471763509371:android:e32aeb3118e518cb4842de',
    messagingSenderId: '471763509371',
    projectId: 'backendcip-874bf',
    storageBucket: 'backendcip-874bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-o8d9aV_dcnV7Y5xIkJe2VZ-hxEe1CY8',
    appId: '1:471763509371:ios:e5c56f8f97c1085f4842de',
    messagingSenderId: '471763509371',
    projectId: 'backendcip-874bf',
    storageBucket: 'backendcip-874bf.firebasestorage.app',
    iosBundleId: 'com.example.cipPaymentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-o8d9aV_dcnV7Y5xIkJe2VZ-hxEe1CY8',
    appId: '1:471763509371:ios:e5c56f8f97c1085f4842de',
    messagingSenderId: '471763509371',
    projectId: 'backendcip-874bf',
    storageBucket: 'backendcip-874bf.firebasestorage.app',
    iosBundleId: 'com.example.cipPaymentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC96VX1CNE8eoRciqZf64GjCXa7FIfsRc4',
    appId: '1:471763509371:web:6e3792e98ae8b1154842de',
    messagingSenderId: '471763509371',
    projectId: 'backendcip-874bf',
    authDomain: 'backendcip-874bf.firebaseapp.com',
    storageBucket: 'backendcip-874bf.firebasestorage.app',
    measurementId: 'G-GRYX9YS6RJ',
  );
}
